//! Single-device, single-hint ingress for a trusted compositor bridge.
//!
//! Peer identity proves a process, not physical origin. Only a bridge whose owned
//! matched-binding callbacks and census are qualified may produce these frames.
//! No reconnect, auto-release, raw dispatcher or standalone effect authority.
use crate::{Batch, Context, Session};
use desktop_io::ProcessIdentity;
use modal_client::{
    data::ProcessGuard,
    presenter::{Auth, Counter},
};
use modal_runtime::socket::{Connection, ControlSocket};
use serde::{Deserialize, Serialize};
use std::{
    io,
    path::Path,
    time::{Duration, Instant},
};
use vimarchy_core::gestures::Event;

#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Frame {
    pub version: u8,
    pub auth: Auth,
    pub bridge_epoch: [u8; 16],
    pub source_revision: Counter,
    pub sequence: Counter,
    /// CLOCK_BOOTTIME milliseconds, same kernel/time namespace as controller.
    pub sent_ms: Counter,
    pub device: Counter,
    pub code: u32,
    pub edge: Edge,
}
#[derive(Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum Edge {
    Ready { held: bool },
    Down,
    Up,
    Cancel,
}

pub struct Gate {
    context: Context,
    auth: Auth,
    epoch: [u8; 16],
    device: u64,
    code: u32,
    hint: String,
    sequence: u64,
    ready: bool,
    held: bool,
    press: Option<u64>,
    last_press: u64,
    last_sent: u64,
    // Once per admission; receipt sampling must not move equal source instants.
    clock_anchor: Option<(u64, u64)>,
    poisoned: bool,
}
fn invalid() -> io::Error {
    io::Error::other("input bridge unavailable")
}
impl Gate {
    /// Epoch must be newly generated by the trusted controller for this admission.
    /// Device/code are a previously established census binding, never peer claims.
    pub fn new(
        context: Context,
        auth: Auth,
        epoch: [u8; 16],
        device: u64,
        code: u32,
        hint: String,
    ) -> io::Result<Self> {
        auth.validate().map_err(io::Error::other)?;
        let namespace = format!(
            "omarchy-modal-{}",
            context
                .presenter
                .iter()
                .map(|b| format!("{b:02x}"))
                .collect::<String>()
        );
        if auth.namespace() != namespace
            || auth.fence() != context.fence
            || epoch == [0; 16]
            || device == 0
            || code == 0
            || code > 767
            || hint.len() != 1
            || !vimarchy_core::allocation::ALPHABET
                .contains(hint.chars().next().ok_or_else(invalid)?)
        {
            return Err(invalid());
        }
        Ok(Self {
            context,
            auth,
            epoch,
            device,
            code,
            hint,
            sequence: 0,
            ready: false,
            held: false,
            press: None,
            last_press: 0,
            last_sent: 0,
            clock_anchor: None,
            poisoned: false,
        })
    }
    pub fn invalidate(&mut self, session: &mut Session) {
        self.poisoned = true;
        self.press = None;
        session.invalidate();
    }
    /// Invalid input revokes the session. Caller must dismiss/release through Host;
    /// discarding Err and continuing another ingress is never recovery.
    pub fn route(
        &mut self,
        bytes: &[u8],
        session: &mut Session,
        boot_ms: u64,
        core_ms: u64,
    ) -> io::Result<Option<Batch>> {
        let result = self.route_inner(bytes, session, boot_ms, core_ms);
        if result.is_err() {
            self.invalidate(session);
        }
        result
    }
    fn route_inner(
        &mut self,
        bytes: &[u8],
        session: &mut Session,
        boot_ms: u64,
        core_ms: u64,
    ) -> io::Result<Option<Batch>> {
        if self.poisoned
            || bytes.len() > 2048
            || session.context() != self.context
            || !session.is_valid()
            || core_ms >= session.deadline
            || core_ms < session.last_now
        {
            return Err(invalid());
        }
        let frame: Frame = serde_json::from_slice(bytes)?;
        let sent = frame.sent_ms.get();
        let age = boot_ms
            .checked_sub(sent)
            .filter(|age| *age <= 40)
            .ok_or_else(invalid)?;
        let event_ms = match self.clock_anchor {
            Some((source_origin, core_origin)) => core_origin
                .checked_add(sent.checked_sub(source_origin).ok_or_else(invalid)?)
                .ok_or_else(invalid)?,
            None => core_ms.checked_sub(age).ok_or_else(invalid)?,
        };
        if frame.version != 1
            || frame.auth != self.auth
            || frame.bridge_epoch != self.epoch
            || frame.source_revision.get() != self.context.source_revision
            || frame.sequence.get() != self.sequence.checked_add(1).ok_or_else(invalid)?
            || frame.device.get() != self.device
            || frame.code != self.code
            || sent < self.last_sent
        {
            return Err(invalid());
        }
        self.sequence = frame.sequence.get();
        self.last_sent = sent;
        let event = match frame.edge {
            Edge::Ready { held } if !self.ready && self.sequence == 1 => {
                self.ready = true;
                self.clock_anchor = Some((sent, event_ms));
                self.held = held;
                None
            }
            Edge::Down if self.ready && !self.held => {
                self.held = true;
                self.last_press = self.last_press.checked_add(1).ok_or_else(invalid)?;
                self.press = Some(self.last_press);
                Some(Event::Down {
                    hint: self.hint.clone(),
                    press_id: self.last_press,
                    alt: false,
                    repeat: false,
                })
            }
            Edge::Up if self.ready && self.held => {
                self.held = false;
                self.press.take().map(|press_id| Event::Up { press_id })
            }
            Edge::Cancel => {
                self.poisoned = true;
                self.press = None;
                Some(Event::Cancel)
            }
            _ => return Err(invalid()),
        };
        session
            .input_at(
                self.context,
                event.unwrap_or(Event::Tick),
                event_ms,
                core_ms,
            )
            .map(Some)
            .map_err(|_| invalid())
    }
}
/// Dedicated private endpoint. One pinned compositor connection, never reconnect.
pub struct Ingress {
    socket: ControlSocket,
    peer: ProcessGuard,
    connection: Option<Connection>,
    gate: Gate,
}
impl Ingress {
    pub fn bind(root: &Path, compositor: ProcessIdentity, gate: Gate) -> io::Result<Self> {
        Ok(Self {
            socket: ControlSocket::bind(root)?,
            peer: ProcessGuard::pin(compositor)?,
            connection: None,
            gate,
        })
    }
    /// Live idle returns None without inventing release or advancing the reducer.
    /// The caller still drives Tick and Host continuity checks. Readiness does not
    /// imply a complete frame: partial frames have one bounded absolute deadline.
    pub fn receive(
        &mut self,
        session: &mut Session,
        core_ms: u64,
        deadline: Instant,
    ) -> io::Result<Option<Batch>> {
        let started = Instant::now();
        let result = (|| {
            if self.gate.poisoned
                || !session.is_valid()
                || session.context() != self.gate.context
                || core_ms < session.last_now
                || core_ms >= session.deadline
                || Instant::now() >= deadline
            {
                return Err(invalid());
            }
            self.peer.check()?;
            if self.connection.is_none() {
                let c = match self.socket.accept() {
                    Ok(c) => c,
                    Err(e) if e.kind() == io::ErrorKind::WouldBlock => return Ok(None),
                    Err(e) => return Err(e),
                };
                self.peer.check_peer(c.uid, c.pid)?;
                self.connection = Some(c);
            }
            let c = self.connection.as_mut().ok_or_else(invalid)?;
            self.peer.check_peer(c.uid, c.pid)?;
            if !c.read_ready()? {
                return Ok(None);
            }
            let bytes = c.read_frame(deadline.min(Instant::now() + Duration::from_millis(40)))?;
            self.peer.check_peer(c.uid, c.pid)?;
            self.gate.route(
                &bytes,
                session,
                boottime_ms()?,
                core_ms
                    .checked_add(
                        started
                            .elapsed()
                            .as_millis()
                            .try_into()
                            .map_err(|_| invalid())?,
                    )
                    .ok_or_else(invalid)?,
            )
        })();
        if result.is_err() {
            self.gate.invalidate(session);
            self.connection = None;
        }
        result
    }
}
pub fn boottime_ms() -> io::Result<u64> {
    let mut ts: libc::timespec = unsafe { std::mem::zeroed() };
    if unsafe { libc::clock_gettime(libc::CLOCK_BOOTTIME, &mut ts) } != 0
        || ts.tv_sec < 0
        || !(0..1_000_000_000).contains(&ts.tv_nsec)
    {
        return Err(invalid());
    }
    (ts.tv_sec as u64)
        .checked_mul(1000)
        .and_then(|s| s.checked_add(ts.tv_nsec as u64 / 1_000_000))
        .ok_or_else(invalid)
}

#[cfg(test)]
mod tests {
    use super::*;
    use modal_contract::{AuthorityEpoch, ClientId, Fence, Owner};
    use std::{collections::BTreeMap, num::NonZeroU64};
    use vimarchy_core::{
        gestures::Effect,
        snapshot::{Client, Monitor, Workspace},
    };
    fn fixture() -> (Gate, Session) {
        let context = Context {
            presenter: [3; 16],
            source_revision: 1,
            fence: Fence {
                authority_epoch: AuthorityEpoch([1; 16]),
                owner: Owner {
                    client: ClientId([2; 16]),
                    client_epoch: NonZeroU64::new(1).unwrap(),
                },
                generation: NonZeroU64::new(1).unwrap(),
            },
        };
        let auth = Auth::new(context.fence, format!("omarchy-modal-{}", "03".repeat(16))).unwrap();
        let gate = Gate::new(context, auth, [4; 16], 1, 30, "a".into()).unwrap();
        let monitors = [Monitor {
            name: "fixture".into(),
            x: 0.,
            y: 0.,
            width: 1280.,
            height: 720.,
            scale: 1.,
            active_workspace: Workspace { id: 1 },
            special_workspace: Workspace { id: 0 },
        }];
        let clients = [Client {
            address: "0x1".into(),
            stable_id: "1".into(),
            mapped: true,
            hidden: false,
            pinned: false,
            workspace: Workspace { id: 1 },
            at: [10., 10.],
            size: [400., 300.],
            grouped: vec![],
            focus_history_id: 0,
        }];
        let (mut session, _) =
            Session::open(context, 1000, 0, &monitors, &clients, &BTreeMap::new(), 280).unwrap();
        session.host_ready(context, 1).unwrap();
        (gate, session)
    }
    fn frame(g: &Gate, seq: u64, now: u64, edge: Edge) -> Vec<u8> {
        serde_json::to_vec(&Frame {
            version: 1,
            auth: g.auth.clone(),
            bridge_epoch: g.epoch,
            source_revision: Counter::new(1).unwrap(),
            sequence: Counter::new(seq).unwrap(),
            sent_ms: Counter::new(now).unwrap(),
            device: Counter::new(1).unwrap(),
            code: 30,
            edge,
        })
        .unwrap()
    }
    fn send(g: &mut Gate, s: &mut Session, seq: u64, now: u64, edge: Edge) -> Vec<Effect> {
        let bytes = frame(g, seq, now, edge);
        let batch = g.route(&bytes, s, now, now).unwrap().unwrap();
        s.consume_batch(batch, now).unwrap()
    }
    #[test]
    fn pinned_socket_idle_then_eof_or_partial_frame_revokes_session() {
        for partial in [false, true] {
            use std::{
                io::Write,
                os::unix::{fs::PermissionsExt, net::UnixStream},
            };
            let (gate, mut session) = fixture();
            let dir = tempfile::tempdir().unwrap();
            std::fs::set_permissions(dir.path(), std::fs::Permissions::from_mode(0o700)).unwrap();
            let stat = std::fs::read_to_string("/proc/self/stat").unwrap();
            let peer = ProcessIdentity {
                pid: std::process::id(),
                start_ticks: stat
                    .rsplit_once(')')
                    .unwrap()
                    .1
                    .split_whitespace()
                    .nth(19)
                    .unwrap()
                    .parse()
                    .unwrap(),
            };
            let ready = frame(
                &gate,
                1,
                boottime_ms().unwrap(),
                Edge::Ready { held: false },
            );
            let mut ingress = Ingress::bind(dir.path(), peer, gate).unwrap();
            assert!(
                ingress
                    .receive(&mut session, 50, Instant::now() + Duration::from_millis(40))
                    .unwrap()
                    .is_none()
            );
            assert!(session.is_valid());
            let mut writer = UnixStream::connect(dir.path().join("modal.sock")).unwrap();
            writer.write_all(&ready).unwrap();
            writer.write_all(b"\n").unwrap();
            let batch = ingress
                .receive(
                    &mut session,
                    100,
                    Instant::now() + Duration::from_millis(40),
                )
                .unwrap()
                .unwrap();
            assert!(batch.effects().is_empty());
            let down = frame(&ingress.gate, 2, boottime_ms().unwrap(), Edge::Down);
            writer.write_all(&down).unwrap();
            writer.write_all(b"\n").unwrap();
            let down = ingress
                .receive(
                    &mut session,
                    200,
                    Instant::now() + Duration::from_millis(40),
                )
                .unwrap()
                .unwrap();
            assert!(!down.effects().iter().any(|e| matches!(e, Effect::Focus(_))));
            assert!(
                ingress
                    .receive(
                        &mut session,
                        250,
                        Instant::now() + Duration::from_millis(40)
                    )
                    .unwrap()
                    .is_none()
            );
            let up = frame(&ingress.gate, 3, boottime_ms().unwrap(), Edge::Up);
            writer.write_all(&up).unwrap();
            writer.write_all(b"\n").unwrap();
            let up = ingress
                .receive(
                    &mut session,
                    300,
                    Instant::now() + Duration::from_millis(40),
                )
                .unwrap()
                .unwrap();
            assert_eq!(
                up.effects()
                    .iter()
                    .filter(|e| matches!(e, Effect::Focus(_)))
                    .count(),
                1
            );
            if partial {
                writer.write_all(b"{").unwrap();
            } else {
                drop(writer);
            }
            assert!(
                ingress
                    .receive(
                        &mut session,
                        301,
                        Instant::now() + Duration::from_millis(40)
                    )
                    .is_err()
            );
            assert!(!session.is_valid());
            assert!(
                ingress
                    .receive(
                        &mut session,
                        302,
                        Instant::now() + Duration::from_millis(40)
                    )
                    .is_err()
            );
        }
    }
    #[test]
    fn queued_same_source_time_edges_survive_later_batch_consumption() {
        let (mut gate, mut session) = fixture();
        send(&mut gate, &mut session, 1, 2, Edge::Ready { held: false });
        let down = frame(&gate, 2, 10, Edge::Down);
        let batch = gate.route(&down, &mut session, 12, 12).unwrap().unwrap();
        session.consume_batch(batch, 13).unwrap();
        let up = frame(&gate, 3, 10, Edge::Up);
        let batch = gate.route(&up, &mut session, 14, 14).unwrap().unwrap();
        let effects = session.consume_batch(batch, 15).unwrap();
        assert_eq!(
            effects
                .iter()
                .filter(|e| matches!(e, Effect::Focus(_)))
                .count(),
            1
        );
    }
    #[test]
    fn equal_source_timestamps_do_not_reverse_under_receipt_sampling_jitter() {
        let (mut gate, mut session) = fixture();
        send(&mut gate, &mut session, 1, 2, Edge::Ready { held: false });
        let down = frame(&gate, 2, 10, Edge::Down);
        let batch = gate.route(&down, &mut session, 12, 12).unwrap().unwrap();
        session.consume_batch(batch, 13).unwrap();
        let up = frame(&gate, 3, 10, Edge::Up);
        let batch = gate.route(&up, &mut session, 15, 14).unwrap().unwrap();
        assert_eq!(
            session
                .consume_batch(batch, 15)
                .unwrap()
                .iter()
                .filter(|e| matches!(e, Effect::Focus(_)))
                .count(),
            1
        );
    }
    #[test]
    fn separate_clocks_preserve_expiry_order_and_pending_revocation() {
        for case in 0..5 {
            let (mut gate, mut session) = fixture();
            send(&mut gate, &mut session, 1, 2, Edge::Ready { held: false });
            let down = frame(&gate, 2, 10, Edge::Down);
            let pending = gate.route(&down, &mut session, 12, 12).unwrap().unwrap();
            if case == 0 {
                assert!(session.consume_batch(pending, 1000).is_err());
                assert!(!session.is_valid());
                continue;
            }
            session.consume_batch(pending, 13).unwrap();
            let superseding = if case == 3 {
                Some(session.input(gate.context, Event::Tick, 20).unwrap())
            } else if case == 4 {
                Some(session.host_ready(gate.context, 20).unwrap())
            } else {
                None
            };
            let (source, receipt) = match case {
                1 => (11, 12),
                2 => (9, 14),
                _ => (15, 21),
            };
            let up = frame(&gate, 3, source, Edge::Up);
            assert!(
                gate.route(&up, &mut session, receipt, receipt).is_err(),
                "case {case}"
            );
            assert!(!session.is_valid());
            if let Some(batch) = superseding {
                assert!(session.consume_batch(batch, 22).is_err());
            }
        }
    }
    #[test]
    fn suspend_clock_divergence_revokes_unconsumed_batch_without_rebase() {
        let (mut gate, mut session) = fixture();
        send(&mut gate, &mut session, 1, 2, Edge::Ready { held: false });
        let down = frame(&gate, 2, 10, Edge::Down);
        let pending = gate.route(&down, &mut session, 12, 12).unwrap().unwrap();
        // BOOTTIME and fresh source timestamp advance while authority/core time
        // does not. The fixed origin maps this into the future; never rebase.
        let up = frame(&gate, 3, 10_010, Edge::Up);
        assert!(gate.route(&up, &mut session, 10_011, 13).is_err());
        assert!(!session.is_valid());
        assert!(session.consume_batch(pending, 14).is_err());
        let rebased = frame(&gate, 4, 15, Edge::Up);
        assert!(gate.route(&rebased, &mut session, 15, 15).is_err());
    }
    #[test]
    fn receipt_delay_does_not_extend_source_double_tap_deadline() {
        let (mut gate, mut session) = fixture();
        send(&mut gate, &mut session, 1, 2, Edge::Ready { held: false });
        let down = frame(&gate, 2, 10, Edge::Down);
        let batch = gate.route(&down, &mut session, 40, 40).unwrap().unwrap();
        session.consume_batch(batch, 40).unwrap();
        let up = frame(&gate, 3, 11, Edge::Up);
        let batch = gate.route(&up, &mut session, 41, 41).unwrap().unwrap();
        session.consume_batch(batch, 41).unwrap();
        let second = frame(&gate, 4, 291, Edge::Down);
        let batch = gate
            .route(&second, &mut session, 292, 292)
            .unwrap()
            .unwrap();
        assert!(
            !session
                .consume_batch(batch, 292)
                .unwrap()
                .iter()
                .any(|e| matches!(e, Effect::DoubleTap { .. }))
        );
    }
    #[test]
    fn constructor_rejects_foreign_presenter_namespace() {
        let (g, _) = fixture();
        let foreign =
            Auth::new(g.context.fence, format!("omarchy-modal-{}", "f".repeat(32))).unwrap();
        assert!(Gate::new(g.context, foreign, g.epoch, 1, 30, "a".into()).is_err());
    }
    #[test]
    fn only_fresh_down_exact_up_can_focus() {
        let (mut g, mut s) = fixture();
        assert!(send(&mut g, &mut s, 1, 2, Edge::Ready { held: true }).is_empty());
        assert!(send(&mut g, &mut s, 2, 3, Edge::Up).is_empty());
        assert!(
            !send(&mut g, &mut s, 3, 4, Edge::Down)
                .iter()
                .any(|e| matches!(e, Effect::Focus(_)))
        );
        assert!(matches!(
            send(&mut g, &mut s, 4, 5, Edge::Up).as_slice(),
            [
                Effect::CancelHold(_),
                Effect::Focus(_),
                Effect::BeginSelection(_)
            ]
        ));
    }
    #[test]
    fn replay_gap_foreign_identity_and_time_poison_session() {
        for case in 0..10 {
            let (mut g, mut s) = fixture();
            send(&mut g, &mut s, 1, 2, Edge::Ready { held: false });
            let mut v: serde_json::Value =
                serde_json::from_slice(&frame(&g, 2, 3, Edge::Down)).unwrap();
            match case {
                0 => v["sequence"] = "1".into(),
                1 => v["sequence"] = "3".into(),
                2 => v["device"] = "2".into(),
                3 => v["code"] = 31.into(),
                4 => v["auth"]["generation"] = "2".into(),
                5 => v["bridge_epoch"][0] = 9.into(),
                6 => v["source_revision"] = "2".into(),
                7 => v["sent_ms"] = "4".into(),
                8 => v["extra"] = true.into(),
                _ => v["edge"] = serde_json::json!({"kind":"up"}),
            };
            assert!(
                g.route(&serde_json::to_vec(&v).unwrap(), &mut s, 3, 3)
                    .is_err(),
                "case {case}"
            );
            assert!(!s.is_valid());
            let valid = frame(&g, 2, 4, Edge::Down);
            assert!(g.route(&valid, &mut s, 4, 4).is_err());
        }
    }
    #[test]
    fn delayed_preheld_repeat_expiry_cancel_and_lost_release_fail_closed() {
        for case in 0..5 {
            let (mut g, mut s) = fixture();
            send(&mut g, &mut s, 1, 2, Edge::Ready { held: case == 0 });
            if case == 0 {
                let f = frame(&g, 2, 3, Edge::Down);
                assert!(g.route(&f, &mut s, 3, 3).is_err());
                continue;
            }
            send(&mut g, &mut s, 2, 3, Edge::Down);
            if case == 1 {
                let f = frame(&g, 3, 4, Edge::Up);
                assert!(g.route(&f, &mut s, 45, 45).is_err());
            }
            if case == 2 {
                let f = frame(&g, 3, 999, Edge::Up);
                assert!(g.route(&f, &mut s, 1001, 1001).is_err());
            }
            if case == 3 {
                let effects = send(&mut g, &mut s, 3, 4, Edge::Cancel);
                assert!(effects.contains(&Effect::Hide));
                let f = frame(&g, 4, 5, Edge::Up);
                assert!(g.route(&f, &mut s, 5, 5).is_err());
            }
            if case == 4 {
                g.invalidate(&mut s);
                let f = frame(&g, 3, 4, Edge::Up);
                assert!(g.route(&f, &mut s, 4, 4).is_err());
            }
            assert!(!s.is_valid());
        }
    }
}
