[package]
name = "modal-client"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
modal-contract = { path = "../modal-contract" }
modal-runtime = { path = "../modal-runtime" }
desktop-io = { path = "../desktop-io" }

[dev-dependencies]
tempfile = "3"
